
name: Java CD with Docker

on:
  push:
    branches: [ "main" ]

  workflow_dispatch: 

jobs:
  
  deploy:

    runs-on: ubuntu_latest

    steps: 
    - uses: actions/checkout@v4
    - run: docker build . -t alamnur/cicd_demo
    - run: echo " ${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - run: docker push alamnur/cicd_demo:latest


